"""empty message

Revision ID: 594b8313b56b
Revises: 243d4b7b3e20
Create Date: 2018-10-01 20:09:03.032443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594b8313b56b'
down_revision = '243d4b7b3e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
